FROM python:3.8
WORKDIR /meme-model-api
COPY . .
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
RUN pip3 install -r base-requirements.txt
RUN pip3 install -r requirements.txt
RUN pip3 install -r requirements_git.txt
EXPOSE 5001
CMD ["python3", "main.py"]
