FROM python:3.8
WORKDIR /asr-api
COPY . .
RUN apt-get update && apt-get install ffmpeg -y
RUN apt-get install libsm6 libxext6 -y
RUN pip3 install -r base-requirements.txt
RUN pip3 install -r requirements.txt
EXPOSE 5004
CMD ["python3", "main.py"]
