FROM python:3.8
WORKDIR /meme-detection-api
COPY . .
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y
RUN pip3 install -r base-requirements.txt
RUN pip3 install -r requirements.txt
EXPOSE 5006
CMD ["python3", "main.py"]
