FROM python:3.8
WORKDIR /target-api
COPY . .
RUN apt-get update && apt-get install screen virtualenv -y
RUN pip3 install -r base-requirements.txt
RUN pip3 install -r requirements.txt
EXPOSE 5005
CMD ["python3", "main.py"]
